version: '3.7'
services:
    php:
        # image: 'php:7.2-fpm'
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: cerberu-php
        volumes:
            - '.:/var/www/html'

    nginx:
        image: nginx:latest
        container_name: cerberu-nginx
        ports:
            - '8082:80'
            - '443:443'
        links:
            - 'php'
        volumes:
            - '.:/var/www/html'
            - './docker/nginx:/etc/nginx/conf.d'

    mariadb:
        image: mariadb:10.3.9
        container_name: cerberu-mariadb
        restart: 'on-failure'
        environment:
            MYSQL_ROOT_PASSWORD: TestCerberu2023
        ports:
            - '3306:3306'
        volumes:
            - ${PWD}
